### ISSUE TITLE
Compilation error: package not in GOROOT

### ISSUE THREAD

**Issue by rnollet** [jech/storrent#12]
First, there is a slight mismatch between the compilation command that is given in the [README](https://github.com/jech/storrent/blob/master/README) (`CGO_ENABLED=1 go build`) and the one given on [storrent webpage](https://www.irif.fr/~jch/software/storrent/) (`go build`). My bug arises with both commands anyway.

When I do `CGO_ENABLED=1 go build`, I get the following:
```
tor/metadata.go:4:2: package cmp is not in GOROOT (/usr/local/go/src/cmp)
dht/dht.go:13:2: package math/rand/v2 is not in GOROOT (/usr/local/go/src/math/rand/v2)
../../../go/pkg/mod/github.com/jackpal/gateway@v1.0.15/gateway_parsers.go:14:2: package slices is not in GOROOT (/usr/local/go/src/slices)
```
and, as far as I can tell, no executable is produced.

I am not a Go programmer, and a bit of research on the internet hasn’t made clear to me whether the problem originates in my installation / configuration (Debian 12, go version go1.19.4 linux/amd64) or in storrent sources.

Do you understand what is happening here, and what could be done to fix it?

**Comment by jech** [comment]
Support for Go 1.9 has been dropped in current master.  So you need to do one of the following:

  - upgrade your Go compiler to version 1.20 or later;
  - downgrade your Galene sources to version 0.9.1.

Since you're running Debian stable, you will find recent Go compilers in the Debian backports repository.  However, installing Go from Google's binaries is pretty trivial, see https://go.dev/doc/install.

In order to downgrade Galene to 0.9.1, simply do

    git checkout galene-0.9.1

in your Git checkout.

**Comment by jech** [comment]
Sorry for the confusion, Rémi.  Storrent requires Go 1.22 or later, since I use it as a testing ground for the latest Go features.

**Comment by jech** [comment]
> First, there is a slight mismatch between the compilation command that is given in the README (CGO_ENABLED=1 go build) and the one given on storrent webpage (go build). My bug arises with both commands anyway.

Right.  `CGO_ENABLED=1` used to be the default when not cross-compiling.  Recent versions of Go have changed the default to be non-deterministic under Windows (I'm only half kidding).  You're not using Windows, are you?

**Comment by rnollet** [comment]
Upgrading to Go 1.23 indeed solved the problem. Thank you for answering so quickly! :-)
