### ISSUE TITLE
Error with installation command

### ISSUE THREAD

**Issue by mtae** [jech/storrent#2]
### **Summary of the problem**
The installation command given in the README is `GO111MODULE=on go install` 
That command gives me an error and does not seem to compile or install storrent.

### **My configuration**
Windows 10
go version go1.17.2 windows/amd64

### **Error log**

[error.log](https://github.com/jech/storrent/files/7450463/error.log)

>  full error output:
> In file included from C:/Users/MyUsername/scoop/apps/gcc/current/lib/gcc/x86_64-w64-mingw32/9.3.0/include/immintrin.h:55,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/lib/gcc/x86_64-w64-mingw32/9.3.0/include/x86intrin.h:32,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/x86_64-w64-mingw32/include/winnt.h:1554,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/x86_64-w64-mingw32/include/minwindef.h:163,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/x86_64-w64-mingw32/include/windef.h:8,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/x86_64-w64-mingw32/include/windows.h:69,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/x86_64-w64-mingw32/include/winsock2.h:23,
>                  from C:/Users/MyUsername/scoop/apps/gcc/current/x86_64-w64-mingw32/include/ws2tcpip.h:17,
>                  from dht\dht.go:40:
> C:/Users/MyUsername/scoop/apps/gcc/current/lib/gcc/x86_64-w64-mingw32/9.3.0/include/avx512fintrin.h: In function '_mm512_mask_reduce_mul_ps':
> C:/Users/MyUsername/scoop/apps/gcc/current/lib/gcc/x86_64-w64-mingw32/9.3.0/include/avx512fintrin.h:15666:3: internal compiler error: Segmentation fault
> 15666 |   __A = _mm512_mask_mov_ps (_mm512_set1_ps (1.0f), __U, __A);
>       |   ^~~
> libbacktrace could not find executable to open

Any advice on how I can build this?

**Comment by jech** [comment]
It looks like the C compiler has crashed.  Perhaps your installation of mingw32 is broken?
