### ISSUE TITLE
Docker hub

### ISSUE THREAD

**Issue by insigmo** [jech/storrent#4]
Can you add to docker hub for fast setup?

**Comment by jech** [comment]
I'm not sure why that would be needed.  Storrent is just a single binary, how is it simpler to deploy using Docker than just launching a binary?

**Comment by gedw99** [comment]
I could add a docker file, so that you can then do what you want from there to build any docker image to and docker container hub.

**Comment by jech** [comment]
I do not use docker, sorry.
