### ISSUE TITLE
blocked ?

### ISSUE THREAD

**Issue by gedw99** [jech/storrent#8]
I am running in default mode and can add magnet links and they appear in the web gui.

but terminal shows this.. SO assume the LAN router is blocked PNP ?

```
2023/12/21 13:15:22 Port mapping: read udp 192.168.1.200:51218->192.168.1.254:5351: recvfrom: connection refused and no UPNP gateways found

```

any tips ???

**Comment by jech** [comment]
It means that your router doesn't support either uPNP or NAT-PMP.  Storrent will still work, but it will not be able to accept any incoming connections, which will dramatically reduce the number of peers and therefore performance.

Please try to enable NAT-PMP or uPNP in your router's administrative interface.  If that is not possible, you may run storrent with the command-line option `-portmap=none`.

**Comment by gedw99** [comment]
Thanks @jech

**Comment by gedw99** [comment]
when I clicked the following in the web gui: Use DHT Passive DHT Use trackers (10) Use webseeds (0) Set, I immediately got peers.

this is without PNP.

**Comment by jech** [comment]
*Use Passive DHT* will make no difference in your case, since you're unreachable.  *Use webseeds* will make no difference since there are 0 webseeds.

Without uPNP or NAT-PNP, you still get seeds, but less than you would if storrent could punch a hole in your NAT.  However, there's nothing to worry about if you have enough peers.

**Comment by gedw99** [comment]
thanks for the explanation. much appreciated @jech

**Comment by jech** [comment]
Could you please try the latest version?  I've just added support for uPNP IGDv2 (a newer portmapping protocol).

**Comment by gedw99** [comment]
hey @jech 

 tried 2 magnet urls and it works much better.

If you need data / metrics let me know.

**Comment by jech** [comment]
Hmm, no change, it looks like your router simply doesn't have any support for NAT-PMP or uPNP, either v1 or v2.  I'm afraid there's nothing to be done at the storrent level.

**Comment by gedw99** [comment]
ok thanks for the feedback.
